# Generated by Django 3.2.5 on 2021-07-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_comment_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='upvotes',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Upvotes'),
        ),
    ]
